#title in header
title: "ê°œë°œì˜ ê¸°ì¨ê³¼ ìŠ¬í””"

#main info
#owner
owner: "Suchan Myoung"
email: aud248@naver.com
info: "1ë…„ì°¨ ë°±ì—”ë“œ ê°œë°œìì…ë‹ˆë‹¤."
#description
desc: "ë¬¸ì œë¥¼ ì •ì˜í•˜ê³  í•´ê²°í•´ ë‚˜ê°€ëŠ” ê³¼ì •ì„ ì¢‹ì•„í•©ë‹ˆë‹¤! ğŸ˜"

#menu
menu:
  Works: /Works
  About: /About

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
github: https://github.com/suchanmyoung

# Misc
nanobar: /js/nanobar.min.js
switch_light: â˜€ï¸
switch_dark: ğŸŒ‘

# Picture enlargement
picjs: /js/pic.min.js

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: true
disqus_shortname: suchanmyoung-github-io
